---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by huang.
--- DateTime: 2025/12/4 16:25
---

-- 加锁脚本
-- KEYS[1]: lockKey
-- ARGV[1]: userId
-- ARGV[2]: ttl (seconds)
-- 逻辑：如果 key 不存在，SETEX；如果 key 存在且值等于 userId，EXPIRE；否则返回 0

if(redis.call("exists", KEYS[1]) == 0) then
    redis.call("set", KEYS[1], ARGV[1], "EX", ARGV[2])
    return true
end
if(redis.call("get", KEYS[1]) == ARGV[1]) then
    redis.call("expire", KEYS[1], ARGV[2])
    return true
end
return false