---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by huang.
--- DateTime: 2025/12/4 16:28
---
-- 解锁脚本
-- KEYS[1]: lockKey
-- ARGV[1]: userId
-- 逻辑：如果 key 存在且值等于 userId，DEL

if (redis.call("get", KEYS[1]) == ARGV[1]) then
    redis.call("del", KEYS[1])
    return true
end
return false